source 'https://rubygems.org'

gem 'rspec', '~> 3.4.0'
gem 'selenium-webdriver', '2.48.1'
gem 'rest-client', '~> 1.8'
gem 'pry', '~> 0.10.3'
gem 'rspec_yah_formatter','~> 0.0.4'
#gem 'rspec_html_formatter','~> 0.3.1'
